$(function(){
    //ตฺ7าณ
    $('#xinrenll2').click(function(){
        $('.foot-box2-img2').addClass("zzz").removeClass('d-none');
        setTimeout(function(){
            window.location.href="../html/index6.html";
        },2000);
    });
});