$(function(){
    //第6页
    $('#xinrenll2').click(function(){
        $('.foot-box2-img2').addClass("zzz").removeClass('d-none');
        setTimeout(function(){
            window.location.href="../html/index1.html";
        },2000);
    });
});